(cl:defpackage navya_control-msg
  (:use )
  (:export
   "<DRIVEACTION>"
   "DRIVEACTION"
   "<DRIVEACTIONFEEDBACK>"
   "DRIVEACTIONFEEDBACK"
   "<DRIVEACTIONGOAL>"
   "DRIVEACTIONGOAL"
   "<DRIVEACTIONRESULT>"
   "DRIVEACTIONRESULT"
   "<DRIVEFEEDBACK>"
   "DRIVEFEEDBACK"
   "<DRIVEGOAL>"
   "DRIVEGOAL"
   "<DRIVERESULT>"
   "DRIVERESULT"
  ))

