; Auto-generated. Do not edit!


(cl:in-package navya_control-msg)


;//! \htmlinclude DriveGoal.msg.html

(cl:defclass <DriveGoal> (roslisp-msg-protocol:ros-message)
  ((dist_2_move
    :reader dist_2_move
    :initarg :dist_2_move
    :type cl:float
    :initform 0.0))
)

(cl:defclass DriveGoal (<DriveGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DriveGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DriveGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name navya_control-msg:<DriveGoal> is deprecated: use navya_control-msg:DriveGoal instead.")))

(cl:ensure-generic-function 'dist_2_move-val :lambda-list '(m))
(cl:defmethod dist_2_move-val ((m <DriveGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader navya_control-msg:dist_2_move-val is deprecated.  Use navya_control-msg:dist_2_move instead.")
  (dist_2_move m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DriveGoal>) ostream)
  "Serializes a message object of type '<DriveGoal>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'dist_2_move))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DriveGoal>) istream)
  "Deserializes a message object of type '<DriveGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'dist_2_move) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DriveGoal>)))
  "Returns string type for a message object of type '<DriveGoal>"
  "navya_control/DriveGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DriveGoal)))
  "Returns string type for a message object of type 'DriveGoal"
  "navya_control/DriveGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DriveGoal>)))
  "Returns md5sum for a message object of type '<DriveGoal>"
  "3bf26d9a45e4f7d2f58daf313ba9d427")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DriveGoal)))
  "Returns md5sum for a message object of type 'DriveGoal"
  "3bf26d9a45e4f7d2f58daf313ba9d427")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DriveGoal>)))
  "Returns full string definition for message of type '<DriveGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%float64 dist_2_move  # Specify which dishwasher we want to use~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DriveGoal)))
  "Returns full string definition for message of type 'DriveGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%float64 dist_2_move  # Specify which dishwasher we want to use~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DriveGoal>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DriveGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'DriveGoal
    (cl:cons ':dist_2_move (dist_2_move msg))
))
