; Auto-generated. Do not edit!


(cl:in-package navya_control-msg)


;//! \htmlinclude DriveResult.msg.html

(cl:defclass <DriveResult> (roslisp-msg-protocol:ros-message)
  ((total_dishes_cleaned
    :reader total_dishes_cleaned
    :initarg :total_dishes_cleaned
    :type cl:float
    :initform 0.0))
)

(cl:defclass DriveResult (<DriveResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DriveResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DriveResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name navya_control-msg:<DriveResult> is deprecated: use navya_control-msg:DriveResult instead.")))

(cl:ensure-generic-function 'total_dishes_cleaned-val :lambda-list '(m))
(cl:defmethod total_dishes_cleaned-val ((m <DriveResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader navya_control-msg:total_dishes_cleaned-val is deprecated.  Use navya_control-msg:total_dishes_cleaned instead.")
  (total_dishes_cleaned m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DriveResult>) ostream)
  "Serializes a message object of type '<DriveResult>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'total_dishes_cleaned))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DriveResult>) istream)
  "Deserializes a message object of type '<DriveResult>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'total_dishes_cleaned) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DriveResult>)))
  "Returns string type for a message object of type '<DriveResult>"
  "navya_control/DriveResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DriveResult)))
  "Returns string type for a message object of type 'DriveResult"
  "navya_control/DriveResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DriveResult>)))
  "Returns md5sum for a message object of type '<DriveResult>"
  "d5197ab31647d52f52a19e26a5a69498")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DriveResult)))
  "Returns md5sum for a message object of type 'DriveResult"
  "d5197ab31647d52f52a19e26a5a69498")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DriveResult>)))
  "Returns full string definition for message of type '<DriveResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%float64 total_dishes_cleaned~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DriveResult)))
  "Returns full string definition for message of type 'DriveResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%float64 total_dishes_cleaned~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DriveResult>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DriveResult>))
  "Converts a ROS message object to a list"
  (cl:list 'DriveResult
    (cl:cons ':total_dishes_cleaned (total_dishes_cleaned msg))
))
