// Auto-generated. Do not edit!

// (in-package navya_control.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class DriveGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.dist_2_move = null;
    }
    else {
      if (initObj.hasOwnProperty('dist_2_move')) {
        this.dist_2_move = initObj.dist_2_move
      }
      else {
        this.dist_2_move = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type DriveGoal
    // Serialize message field [dist_2_move]
    bufferOffset = _serializer.float64(obj.dist_2_move, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type DriveGoal
    let len;
    let data = new DriveGoal(null);
    // Deserialize message field [dist_2_move]
    data.dist_2_move = _deserializer.float64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'navya_control/DriveGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '3bf26d9a45e4f7d2f58daf313ba9d427';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the goal
    float64 dist_2_move  # Specify which dishwasher we want to use
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new DriveGoal(null);
    if (msg.dist_2_move !== undefined) {
      resolved.dist_2_move = msg.dist_2_move;
    }
    else {
      resolved.dist_2_move = 0.0
    }

    return resolved;
    }
};

module.exports = DriveGoal;
