// Generated by gencpp from file navya_control/DriveGoal.msg
// DO NOT EDIT!


#ifndef NAVYA_CONTROL_MESSAGE_DRIVEGOAL_H
#define NAVYA_CONTROL_MESSAGE_DRIVEGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace navya_control
{
template <class ContainerAllocator>
struct DriveGoal_
{
  typedef DriveGoal_<ContainerAllocator> Type;

  DriveGoal_()
    : dist_2_move(0.0)  {
    }
  DriveGoal_(const ContainerAllocator& _alloc)
    : dist_2_move(0.0)  {
  (void)_alloc;
    }



   typedef double _dist_2_move_type;
  _dist_2_move_type dist_2_move;




  typedef boost::shared_ptr< ::navya_control::DriveGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navya_control::DriveGoal_<ContainerAllocator> const> ConstPtr;

}; // struct DriveGoal_

typedef ::navya_control::DriveGoal_<std::allocator<void> > DriveGoal;

typedef boost::shared_ptr< ::navya_control::DriveGoal > DriveGoalPtr;
typedef boost::shared_ptr< ::navya_control::DriveGoal const> DriveGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navya_control::DriveGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navya_control::DriveGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace navya_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'navya_control': ['/home/darling/Desktop/navya_working_copy/devel/share/navya_control/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::navya_control::DriveGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navya_control::DriveGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navya_control::DriveGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navya_control::DriveGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navya_control::DriveGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navya_control::DriveGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navya_control::DriveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3bf26d9a45e4f7d2f58daf313ba9d427";
  }

  static const char* value(const ::navya_control::DriveGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3bf26d9a45e4f7d2ULL;
  static const uint64_t static_value2 = 0xf58daf313ba9d427ULL;
};

template<class ContainerAllocator>
struct DataType< ::navya_control::DriveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navya_control/DriveGoal";
  }

  static const char* value(const ::navya_control::DriveGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navya_control::DriveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the goal\n\
float64 dist_2_move  # Specify which dishwasher we want to use\n\
";
  }

  static const char* value(const ::navya_control::DriveGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navya_control::DriveGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dist_2_move);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DriveGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navya_control::DriveGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navya_control::DriveGoal_<ContainerAllocator>& v)
  {
    s << indent << "dist_2_move: ";
    Printer<double>::stream(s, indent + "  ", v.dist_2_move);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVYA_CONTROL_MESSAGE_DRIVEGOAL_H
